[package]
name = "tukaj"
version = "0.0.1"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = { version = "0.28.1", features = ["event-stream"] }
rand = "0.8.5"
ratatui = "0.28.1"
tokio = { version = "1.41.0", features = ["full"] }
